---
title: "Usage examples"
---

NOTE: Be sure to test these in release mode! Use `devtools::install()` to switch into it.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(unsum)
```

## CLOSURE

3,800,640 values in a few seconds:
```{r}
closure_generate(
  mean = "3.8",
  sd = "1.5",
  n = 120,
  scale_min = 1,
  scale_max = 5
)
```

16,701,150 values in a few seconds:
```{r}
closure_generate(
  mean = "3.0",
  sd = "1.0",
  n = 150,
  scale_min = 1,
  scale_max = 5
)
```

25,278,450 values in a few seconds:
```{r}
closure_generate(
  mean = "3.0",
  sd = "1.5",
  n = 150,
  scale_min = 1,
  scale_max = 5
)
```

31,235,760 values in a few seconds:
```{r}
closure_generate(
    mean = "3.0",
    sd = "1.7",
    n = 180,
    scale_min = 1,
    scale_max = 5
)
```

38,740,810 values in a few seconds:
```{r}
closure_generate(
    mean = "3.0",
    sd = "1.7",
    n = 190,
    scale_min = 1,
    scale_max = 5
)
```

52,231,000 values in a few seconds:
```{r}
closure_generate(
    mean = "3.0",
    sd = "1.7",
    n = 200,
    scale_min = 1,
    scale_max = 5
)
```

132,389,600 values in less than 3 seconds:
```{r}
closure_generate(
    mean = "3.0",
    sd = "1.2",
    n = 200,
    scale_min = 1,
    scale_max = 5
)
```
