---
title: "Proving the correctness of the horns index"
subtitle: "Deriving formulas for the general case ($h$) and the uniform distribution ($h_u$)"
output:
  html_document:
    df_print: paged
    number_sections: true
    mathjax: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    pandoc_args: ["--mathjax"]
  pdf_document:
    extra_dependencies: ["amsmath"]
    number_sections: false
    keep_tex: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

TODO: MAKE THE HORNS INDEX DEPENDENT ON N, SETTLE ON A NEW NOTATION FOR THE N-INDEPENDENT MEASURE THAT WILL NOW TAKE A BACKSEAT, IMPLEMENT A NEW N-DEPENDENT `horns()` FUNCTION, AND RENAME THE EXISTING FUNCTION TO `horns_inf_n()`.

The horns index, $h$, depends on the sample size, $n$. However, we can define $h^*$ as a variant of $h$ that does not take $n$ into account. This variant represents $h$ in case of an infinite $n$ value.

Because small samples increase the maximum possible variance, and because the latter constitutes the denominator of $h$, taking $n$ into account decreases $h$ inversely proportional to $n$. In other words, $h$ approaches $h^*$ as $n$ tends to infinity.

Thus, $h^*$ is the variance as a proportion of the maximum variance that can be achieved by a distribution with given scale bounds and any sample size, rather than some particular finite sample size. In unsum, $h^*$ is implemented in the `horns_inf_n()` function.

$h_{u,\infty}$

$h^*_u$

***

The horns index ($h$) is the variance expressed as a proportion of the maximum variance that is possible with a given set of lower and upper bounds. It is defined as

\begin{equation}
h = \frac
{\sigma^2}
{\frac{1}{4} (u - l)^2}
\end{equation}

where $\sigma^2$ is the variance, $l$ is the lower bound, and $u$ is the upper bound. The horns index follows from Popoviciu's inequality (see below).

For discrete distributions, this can be expressed as

\begin{equation}
h = \frac
{\sum_{i=1}^{k} \ f_i \ (i - \bar{s})^2}
{\frac{1}{4} (k - 1)^2}
\end{equation}

where $k$ is the number of scale points, $f_i$ is the relative frequency of the $i$th point on an ordinal scale from $1$ to $k$ (both inclusive), and $\bar{s}$ is the scale mean.

The numerator ranges from $0$ to $\frac{1}{4} (k - 1)^2$, so its upper bound is determined by the scale bounds. These may follow from the number of scale points, $k$ (e.g., with a Likert scale). Alternatively, they can be the empirical minimum and maximum values rescaled to fit the range from $1$ to $k$.

For a scale with bounds $1$ and $k$, the maximum dispersion occurs if 50% of the data points are at $1$ and 50% are at $k$. The same applies to any scale with $k$ points, and the resultant $h$ will be equal because its value only depends on the frequency distribution, not the original scale values. As an intuitive example, imagine a histogram of values on a scale from 21 to 27. The frequencies depicted in the histogram would remain the same if the 21-27 labels were replaced by 1-7 labels, or labels corresponding to any other 7-point ordinal scale.

### The denominator is the maximum possible variance given scale limits

Let $\bar{s}_{\max}$ and $\sigma^2_{\max}$ be the mean and the variance in this maximal scenario. The mean is the midpoint, i.e.,

\begin{equation}
\bar{s}_{\max} = \frac{k + 1}{2}
\end{equation}

The variance is the mean squared deviation of the two extreme values:

\begin{equation}
\sigma^2_{\max} = \frac{1}{2} \ \left[ (1 - \bar{s})^2 + (k - \bar{s})^2 \right]
\end{equation}

Substituting the mean yields

\begin{equation}
\sigma^2_{\max} = \frac{1}{2} \ \left[ \left( 1 - \frac{k + 1}{2} \right)^2 + \left( k - \frac{k + 1}{2} \right) ^2 \right]
\end{equation}

Simplifying the first term:

\begin{align}
\left( 1 - \frac{k + 1}{2} \right)^2
  &= \left( 1 - \frac{k}{2} - \frac{1}{2} \right)^2 \\
  &= \left( \frac{1}{2} - \frac{k}{2} \right)^2 \\
  &= \left( \frac{1 - k}{2} \right)^2 \\
  &= \frac{1}{4} \ (1 - k)^2
\end{align}

Simplifying the second term:

\begin{align}
\left( k - \frac{k + 1}{2} \right)^2 &= \left( k - \frac{k}{2} - \frac{1}{2} \right)^2 \\
  &= \left( \frac{k}{2} - \frac{1}{2} \right)^2 \\
  &= \left( \frac{k - 1}{2} \right)^2 \\
  &= \frac{1}{4} \ (k - 1)^2
\end{align}

Due to squaring, the first term equals the second, and it follows that it is equal to the maximum variance:

\begin{align}
\sigma^2_{\max} &= \frac{1}{2} \ \left[ \frac{1}{4} \ (k - 1)^2 + \frac{1}{4} \ (k - 1)^2 \right] \\
  &= \frac{1}{4} \ (k - 1)^2
\end{align}

$\square$

This is simply the upper bound imposed by Popoviciu's inequality, which asserts that

\begin{equation}
\sigma^2 \leq \frac{1}{4} \ (u - l)^2
\end{equation}

where $l$ is the lower bound and $u$ is the upper bound. In the present context of ordinal scales, the range $u - l$ is equal to $k - 1$ for any $k$-point scale, even in cases where $u \neq k$ and $l \neq 1$.

### The numerator is the extent to which the actual variance approximates the maximum possible variance given scale limits

The numerator is the weighted sum of squares. The mean $\bar{s}$ is derived from the relative frequencies:

\begin{equation}
\bar{s} = \sum_{i=1}^{k} i \ f_i
\end{equation}

In the maximal case, $f_i$ is $\frac{1}{2}$ at both extremes, $1$ and $k$; but $0$ at all other points. Thus, the weighted sum of squares is the sum of two terms only. The mean, $\bar{s}$, is $\bar{s}_{max}$ from (2.1), i.e., $\frac{k + 1}{2}$.

From (2.5), it trivially follows that, for $f_1 = f_k = \frac{1}{2}$,

\begin{align}
\sum_{i=1}^{k} f_i \ (i - \bar{s})^2 &= \frac{1}{2} \left(1 - \frac{k + 1}{2} \right)^2 + \frac{1}{2} \left(k - \frac{k + 1}{2} \right)^2 \\
  &= 2 \left[ \frac{1}{2} \left(k - \frac{k + 1}{2} \right)^2 \right] \\
  &= \left(k - \frac{k + 1}{2} \right)^2 \\
  &= \frac{1}{4} \ (k - 1)^2
\end{align}

Thus, in the maximal case, the numerator of the $h$ formula in (1) is equal to the denominator, and $h$ equals $1$.

$\square$

#### Separate, equivalent proof

The following again holds for $f_1 = f_k = \frac{1}{2}$.

With $i = 1$ and using (2.4):

\begin{align}
\frac{1}{2} \left( 1 - \frac{k + 1}{2} \right)^2 &= \frac{1}{2} \left( \frac{2 - (k + 1)}{2} \right)^2 \\
  &= \frac{1}{2} \cdot \frac{(1 - k)^2}{4} \\
  &= \frac{(k - 1)^2}{8}
\end{align}

With $i = k$ and using (2.5):

\begin{align}
\frac{1}{2} \left( k - \frac{k + 1}{2} \right)^2 &= \frac{1}{2} \left( \frac{2k - (k + 1)}{2} \right)^2 \\
  &= \frac{1}{2} \cdot \frac{(k - 1)^2}{4} \\
  &= \frac{(k - 1)^2}{8}
\end{align}

Therefore, the same result as above obtains:

\begin{align}
\sum_{i=1}^{k} f_i \ (i - \bar{s})^2 &= 2 \ \frac{(k - 1)^2}{8} \\
  &= \frac{1}{4} \ (k - 1)^2
\end{align}

$\square$

Conversely, in the minimal case, all observations have the same value. The sum of squares is trivially $0$, and so is $h$. In the same way, $h$ is never negative because the sum of squares never is.

### The $h$ of a uniform distribution can be obtained using the $h_u$ formula

In the case of a discrete uniform distribution, $h$ can be expressed as follows:

\begin{equation}
h_u = \frac{k + 1}{3 \ (k - 1)}
\end{equation}

The variance of the discrete uniform distribution, $\sigma_u^2$, is given in [Proof Wiki (2021)](https://proofwiki.org/wiki/Variance_of_Discrete_Uniform_Distribution) using a different notation (e.g., $n$ instead of our $k$):

\begin{equation}
\sigma_u^2 = \frac{1}{12} \ (k^2 - 1)
\end{equation}

Note that $k^2 - 1$ can be expanded to $(k - 1) \ (k + 1)$:

\begin{align}
(k - 1) \ (k + 1) &= k \ (k + 1) - 1 \ (k + 1) \\
  &= k^2 + k - k - 1 \\
  &= k^2 - 1
\end{align}

The derivation of $h_u$, then, is straightforward:

\begin{align}
h_u &= \frac{ \frac{1}{12} (k^2 - 1) }{ \frac{1}{4} (k - 1)^2 } \\
  &= \frac{ (k - 1) \ (k + 1) }{12} \cdot \frac{4}{ (k - 1)^2 } \\
  &= \frac{4 \ (k + 1)}{12 \ (k - 1)} \\
  &= \frac{k + 1}{3 \ (k - 1)}
\end{align}

$\square$

Alternatively, this can be shown as follows:

\begin{align}
h_u &= \frac{ \frac{1}{12} (k^2 - 1) }{ \frac{1}{4} (k - 1)^2 } \\
  &= 4 \ \frac{ \frac{1}{12} (k^2 - 1) }{ (k - 1)^2 } \\
  &= \frac{1}{3} \cdot \frac{k^2 - 1}{(k - 1)^2} \\
  &= \frac{(k - 1) \ (k + 1)}{3 \ (k - 1) ^2} \\
  &= \frac{k + 1}{3 \ (k - 1)}
\end{align}

$\square$

#### Another proof of the $h_u$ formula

This proof focuses on the sum of squares. It does not rely on the $\sigma_u^2$ formula from (4.2).

In the uniform case, all (relative) frequencies are equal:

\begin{equation}
\forall \ i \in \{ 1, \ 2, \ ..., \ k \}: \ f_i = \frac{1}{k}
\end{equation}

Therefore:

\begin{align}
h_u &= \frac
{\sum_{i=1}^{k} \ \frac{1}{k} \ (i - \bar{s})^2}
{\frac{1}{4} (k - 1)^2} \\
  &= \frac{1}{k} \left[ 4 \ \frac
{\sum_{i=1}^{k} \ (i - \bar{s})^2}
{(k - 1)^2} \right] \\
  &= 4 \ \frac{\sum_{i=1}^{k} \ (i - \bar{s})^2}{k (k - 1)^2}
\end{align}

Simplifying the sum of squares:

\begin{align}
\sum_{i=1}^{k} (i - \bar{s})^2 &= \sum_{i=1}^{k} (i^2 - 2i\bar{s} + \bar{s}^2) \\
  &= \sum_{i=1}^{k} i^2 - 2\bar{s}\sum_{i=1}^{k} i + \sum_{i=1}^{k} \bar{s}^2 \\
  &= \sum_{i=1}^{k} i^2 - 2\bar{s} \cdot k\bar{s} + k\bar{s}^2 \\
  &= \sum_{i=1}^{k} i^2 - 2k\bar{s}^2 + k\bar{s}^2 \\
  &= \sum_{i=1}^{k} i^2 - k\bar{s}^2
\end{align}

For the left-hand term, we use the formula for the sum of squares of the first $k$ natural numbers:

\begin{equation}
\sum_{i=1}^{k} i^2 = \frac{k(k+1)(2k+1)}{6}
\end{equation}

The mean $\bar{s}$ of the uniform distribution is simply the scale midpoint, as in (2.1):

\begin{align}
\bar{s} &= \frac{k+1}{2}
\end{align}

So the term subtracted within the expression established in (4.8) is

\begin{align}
k \bar{s}^2 &= k \left(\frac{k+1}{2}\right)^2 \\
&= \frac{k (k+1)^2}{4}
\end{align}

Inserting (4.8), followed by (4.9) and (4.11):

\begin{align}
h_u &= 4 \frac{\sum_{i=1}^{k} (i - \bar{s})^2}{k(k-1)^2} \\
  &= 4 \frac{\sum_{i=1}^{k} i^2 - k\bar{s}^2}{k(k-1)^2} \\
  &= 4 \frac{1}{k(k-1)^2} \left[ \frac{k(k+1)(2k+1)}{6} - \frac{k(k+1)^2}{4} \right] \\
  &= 4 \frac{k(k+1)}{k(k-1)^2} \left[\frac{2k+1}{6} - \frac{k+1}{4}\right]
\end{align}

Simplifying the right-hand term:

\begin{align}
\frac{2k+1}{6} - \frac{k+1}{4} &= \frac{2(2k+1) - 3(k+1)}{12} \\
  &= \frac{4k+2 - 3k-3}{12} \\
  &= \frac{k-1}{12}
\end{align}

Simplifying (4.12) and inserting (4.13) makes the final steps easy:

\begin{align}
h_u &= 4 \frac{k+1}{(k-1)^2} \cdot \frac{k-1}{12} \\
  &= 4 \frac{(k+1)(k-1)}{12(k-1)^2} \\
  &= 4 \frac{k+1}{12(k-1)} \\
  &= \frac{k+1}{3(k-1)}
\end{align}

$\square$

#### $h_u$ is constant in the continuous case

The horns index of the continuous uniform distribution, $h_u$, is a constant:

\begin{equation}
h_u = \frac{1}{3}, \ \ k = \infty
\end{equation}

Let $l$ be the lower bound and $u$ the upper bound. The variance of the continuous uniform distribution is ([Proof Wiki 2023](https://proofwiki.org/wiki/Variance_of_Continuous_Uniform_Distribution)):

\begin{equation}
\sigma^2 = \frac{1}{12} (u - l)^2
\end{equation}

We will similarly express the maximum possible variance from Popoviciu's inequality in terms of $l$ and $u$ (rather than $1$ and $k$, which was only sensible for the ordinal distribution):

\begin{align}
\sigma^2_{\max} = \frac{1}{4} (u - l)^2
\end{align}

So the horns index in this case is constant at $\frac{1}{3}$:

\begin{align}
h_u &= \frac
{ \frac{1}{12} (u - l)^2 }
{ \frac{1}{4} (u - l)^2 } \\
  &= \frac{1}{3}
\end{align}

#### $h_u$ converges to $\frac{1}{3}$ as $k$ increases

Finally, $h_u$ asymptotically approximates $\frac{1}{3}$:

\begin{equation}
\lim_{k \to \infty} h_u = \frac{1}{3}
\end{equation}

We will first transform $h_u$:

\begin{align}
h_u &= \frac{k+1}{3(k-1)} \\
  &= \frac
{k (1 + \frac{1}{k})}
{k (3 - \frac{3}{k})} \\
  &= \frac
{1 + \frac{1}{k}}
{3 - \frac{3}{k}}
\end{align}

Therefore, as $k$ increases, $h_u$ approaches $\frac{1}{3}$:

\begin{equation}
\lim_{k \to \infty} \frac
{1 + \frac{1}{k}}
{3 - \frac{3}{k}} = \frac{1}{3}
\end{equation}

$\square$
