# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_unsum_wrappers", use_symbols = TRUE, package_name = "unsum")

#' @usage NULL
#' @useDynLib unsum, .registration = TRUE
NULL

create_combinations <- function(mean, sd, n, scale_min, scale_max, technique, rounding_error_mean, rounding_error_sd, items, restrict_exact, restrict_min, write, stop_after) .Call(wrap__create_combinations, mean, sd, n, scale_min, scale_max, technique, rounding_error_mean, rounding_error_sd, items, restrict_exact, restrict_min, write, stop_after)

create_empty_results <- function(scale_min, scale_max) .Call(wrap__create_empty_results, scale_min, scale_max)

count_closure_combinations <- function(mean, sd, n, scale_min, scale_max, rounding_error_mean, rounding_error_sd) .Call(wrap__count_closure_combinations, mean, sd, n, scale_min, scale_max, rounding_error_mean, rounding_error_sd)


# nolint end
